
import { AuthProvider } from "@/contexts/auth.context";
import { CartProvider } from "@/contexts/cart.context";
import { OrderProvider } from "@/contexts/order.context";
import ReduxProvider from "@/redux/ReduxProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from 'react-toastify';
import "./globals.css";
import { NetworkStatusProvider } from "@/contexts/network.context";
import ChatBox from "@/components/pages/ChatBox";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NetworkStatusProvider>
          <ReduxProvider>
            <AuthProvider>
              <CartProvider>
                <OrderProvider>
                  <ToastContainer />

                  {children}
                  <ChatBox />
                </OrderProvider>
              </CartProvider>
            </AuthProvider>
          </ReduxProvider>
        </NetworkStatusProvider>
      </body>
    </html>
  );
}
