export const DETAIL_PRODUCT_URL = "/detailproduct"
export const CART_URL = "/cart"
export const ORDER_URL = "/order"
export const PURCHASE_URL = "/purchase/order"
export const CATEGORY_URL = "/category"
export const CHECKOUT_URL = "/checkout"
export const SEARCH_URL = "/search/"
export const EDIT_PHONE_URL = "/customer/edit"
export const EDIT_EMAIL_URL = "/customer/edit"
export const CHANGE_PASSWORD_URL = "/customer/account/edit/password"


// Auth
export const LOGIN_URL = "/auth/login"
export const LOGOUT_URL = "/auth/logout"
export const REGISTER_URL = "/auth/register"
export const FORGOT_PASSWORD_URL = "/customer/account/forgot_password"
export const RESET_PASSWORD_URL = "//customer/account/reset_password"
export const PROFILE_URL = "/customer/account"
export const UPDATE_PROFILE_URL = "/auth/update-profile"
export const UPDATE_PASSWORD_URL = "/auth/update-password"
